name: "Check CodeDeploy Status"
description: "Checks AWS CodeDeploy deployment status and fails if not successful"
author: "Your Name or Org"

inputs:
  aws-region:
    required: true
    description: "AWS region"
  aws-role-to-assume:
    required: true
    description: "AWS Role ARN to assume"
  codedeploy-app-name:
    required: true
    description: "CodeDeploy application name"
  codedeploy-deployment-group:
    required: true
    description: "CodeDeploy deployment group name"

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws-role-to-assume }}
        aws-region: ${{ inputs.aws-region }}

    - name: Check CodeDeploy Deployment Status
      shell: bash
      run: |
        APP="${{ inputs.codedeploy-app-name }}"
        DG="${{ inputs.codedeploy-deployment-group }}"

        # Get latest deployment ID
        DEPLOYMENT_ID=$(aws deploy list-deployments \
                          --application-name "$APP" \
                          --deployment-group-name "$DG" \
                          --query "deployments[0]" \
                          --output text)

        if [ "$DEPLOYMENT_ID" == "None" ]; then
          echo "⚠️ No CodeDeploy deployments found"
          exit 1
        fi

        echo "Waiting for CodeDeploy deployment $DEPLOYMENT_ID to complete..."
        aws deploy wait deployment-successful --deployment-id "$DEPLOYMENT_ID"

        echo "✅ CodeDeploy deployment succeeded!"