name: "Build and Push Docker to ECR"
description: "Reusable composite action to build and push Docker image to AWS ECR"
author: "Your Name or Org"

permissions:
  id-token: write

inputs:
  service:
    description: "The service name (e.g., frontend or backend)"
    required: true
  environment:
    description: "Deployment environment (develop, staging, prod)"
    required: true
  image_tag:
    description: "Image tag to push (e.g., SHA, latest)"
    required: false
    default: "latest"
  aws-region:
    description: "AWS region for ECR"
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials from OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
        aws-region: ${{ inputs.aws-region }}

    - name: Login to Amazon ECR
      shell: bash
      run: |
        aws ecr get-login-password --region ${{ inputs.aws-region }} \
          | docker login --username AWS \
          --password-stdin ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com

    - name: Build Docker image
      shell: bash
      run: |
        docker build -t ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com/${{ inputs.service }}/${{ inputs.environment }}:${{ inputs.image_tag }} .
        docker tag ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com/${{ inputs.service }}/${{ inputs.environment }}:latest .

    - name: Push Docker image
      shell: bash
      run: |
        docker push ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com/${{ inputs.service }}/${{ inputs.environment }}:${{ inputs.image_tag }}
